=head1 NAME

mogilefsd - A munin plugin that collects stats from your MogileFS tracker

=head1 APPLICABLE SYSTEMS

MogileFS Trackers

=head1 CONFIGURATION

By default the plugin will check localhost, port 7001. If you want to change the port set the following in your config:

    [mogilefsd]
	env.mog_port 7001

If you'd like to test a different host, then symlink the script with an
underscored followed by the hostname or IP.

    ln -s /usr/share/munin/plugins/mogilefsd /etc/munin/plugins/mogilefsd_tracker1.domain.com

=head1 BUGS

None known so far. If you find any, let me know.

=head1 AUTHOR

Squeeks - squeek@cpan.org - L<http://github.com/squeeks>

=head1 LICENSE

Licensed under the MIT license: L<http://www.opensource.org/licenses/mit-license.php>

=cut
